# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ia_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ia_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ia_service.proto\x12\x0f\x62r.com.camplana\"E\n\rPromptRequest\x12\x12\n\nusuario_id\x18\x01 \x01(\x05\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x10\n\x08\x63ontexto\x18\x03 \x01(\t\"=\n\x0ePromptResponse\x12\x10\n\x08resposta\x18\x01 \x01(\t\x12\x19\n\x11tokens_utilizados\x18\x02 \x01(\x05\x32]\n\tIAService\x12P\n\rGerarResposta\x12\x1e.br.com.camplana.PromptRequest\x1a\x1f.br.com.camplana.PromptResponseB\x13\n\x0f\x62r.com.camplanaP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ia_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017br.com.camplanaP\001'
  _globals['_PROMPTREQUEST']._serialized_start=37
  _globals['_PROMPTREQUEST']._serialized_end=106
  _globals['_PROMPTRESPONSE']._serialized_start=108
  _globals['_PROMPTRESPONSE']._serialized_end=169
  _globals['_IASERVICE']._serialized_start=171
  _globals['_IASERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
